# replace values below with appropriate values as per documentation.
# Parsely API key and shared secret can be found in the dashboard in "Settings"->"API"
# Parsely apikey
apikey: example.com

#parsely shared_secret
shared_secret: abcdef12345

# slack team id- can find this at https://api.slack.com/methods/team.info/test
team_id: T12345

# Slack slash commands integration token
slack_token: abcdef12345

# posts to return for each query
limit: 5

# if threshold is greater than zero and webhook is set,
# the minimum pageviews in the last 5 minutes to trigger a trending alert
# to the listed channels
webhook_url: https://hooks.slack.com/services/T12345/example12345
threshold: 0
# channels:
# - "#general"
# - "#example"
